import {readFile, writeFile, mkdir, cp, readdir, rm} from 'node:fs/promises';
import {createHash} from 'node:crypto';
import {spawnSync} from 'node:child_process';
import {resolve, join, relative} from 'node:path';
import {fileURLToPath} from 'node:url';
import {build} from '../../runtime/node_modules/esbuild/lib/main.js';

const root = resolve(process.argv[2] || '');
if (process.argv.length !== 3) throw new Error('Usage: node build.mjs <pinned-upstream-checkout>');
const pin = '1bd90d3adb449a94bdff3dec04d01884fe335546';
for (const args of [['rev-parse', 'HEAD'], ['diff', '--exit-code', 'HEAD', '--', 'app']]) {
  const result = spawnSync('git', ['-C', root, ...args], {encoding: 'utf8'});
  if (result.status !== 0 || (args[0] === 'rev-parse' && result.stdout.trim() !== pin)) throw new Error('Unpinned or edited upstream source');
}
const here = fileURLToPath(new URL('.', import.meta.url));
const assets = join(here, 'build/assets');
// This fixed path is exclusively generated by this sample builder.
await rm(assets, {recursive: true, force: true});
await mkdir(assets, {recursive: true});
const source = join(root, 'app'), domain = join(assets, 'electron_app'), browser = join(assets, 'calculator');
const metadata = JSON.parse(await readFile(join(source, 'package.json'), 'utf8'));
if (metadata.version !== '1.1.4') throw new Error('Unexpected app version');
const logger = JSON.parse(await readFile(join(source, 'node_modules/electron-log/package.json'), 'utf8'));
if (logger.version !== '5.1.1') throw new Error('Install pinned upstream production dependencies first');
await mkdir(domain, {recursive: true}); await mkdir(browser, {recursive: true});
for (const name of await readdir(source)) {
  if (name === 'node_modules') continue;
  await cp(join(source, name), join(domain, name), {recursive: true});
  if (!['app.js', 'preload.js', 'package.json', 'package-lock.json'].includes(name)) {
    await cp(join(source, name), join(browser, name), {recursive: true});
  }
}
const loggerRoot = join(source, 'node_modules/electron-log');
await cp(loggerRoot, join(domain, 'node_modules/electron-log'), {
  recursive: true,
  // Dependency tests are not runtime resources; AAPT omits underscore-prefixed
  // directories, so inventorying __specs__ made native extraction fail.
  filter: path => !relative(loggerRoot, path).split(/[\\/]/).some(part => part.startsWith('.') || part === '__specs__' || part === '__specs'),
});
await cp(join(here, 'electromux.json'), join(domain, 'electromux.json'));
// Execute unchanged preload in a lexical metadata-only scope before app scripts.
const preload = await readFile(join(source, 'preload.js'), 'utf8');
const script = '(function(){const snapshot=' + JSON.stringify({version: metadata.version, versions: {electromux: '0.0.1'}}) +
  ';const process=Object.freeze({versions:Object.freeze(snapshot.versions)});const remote=Object.freeze({app:Object.freeze({getVersion:()=>snapshot.version})});' +
  "const require=id=>{if(id==='@electron/remote')return remote;throw new Error('Unsupported preload module: '+id);};" +
  '(function(require,process){\n' + preload + '\n})(require,process);})();' +
  "(function(){const send=(method,message)=>window.cefriumQuery({request:JSON.stringify({method,message}),onSuccess:()=>{},onFailure:(code,error)=>console.error('Electromux document signal failed',code,error)});" +
  "window.addEventListener('DOMContentLoaded',()=>send('electromux.document.ready',''));" +
  "window.addEventListener('error',event=>send('electromux.document.failed',String(event.message||'Renderer resource error').slice(0,512)));" +
  "window.addEventListener('unhandledrejection',event=>send('electromux.document.failed',String(event.reason?.stack||event.reason||'Renderer promise failed').slice(0,512)));})();";
const hash = createHash('sha256').update(script).digest('base64');
let html = await readFile(join(source, 'index.html'), 'utf8');
if (!html.includes("script-src ") || !html.includes('</head>') || /<\/script/i.test(script)) throw new Error('Unsupported HTML/preload publication shape');
html = html.replace('script-src ', `script-src 'sha256-${hash}' `).replace('</head>', `<script>${script}</script></head>`);
await writeFile(join(browser, 'index.html'), html);
const resources = [];
async function inventory(directory, prefix) {
  for (const entry of await readdir(directory, {withFileTypes: true})) {
    if (entry.isSymbolicLink()) throw new Error('Resource symlink rejected');
    const path = `${prefix}/${entry.name}`;
    if (entry.isDirectory()) await inventory(join(directory, entry.name), path); else resources.push(path);
  }
}
await inventory(domain, 'electron_app');
if (resources.length > 512) throw new Error('Resource inventory exceeds native limit');
await writeFile(join(assets, 'calculator-resources.json'), JSON.stringify(resources));
await mkdir(join(assets, 'embedded_node'), {recursive: true});
await build({entryPoints: [join(here, 'entry.ts')], outfile: join(assets, 'embedded_node/calculator.mjs'),
  bundle: true, platform: 'node', format: 'esm', target: 'node24'});
console.log(`Packaged unchanged calculator entrypoints at ${pin}; ${resources.length} domain resources`);
